######################################
## Site settings                    ##
######################################
title: Fullstack Junior developer |Amateur Photographer| Tech Addict
email: Andry1287@gmail.com
author: Andry Rajohnson
description: "Project I've made where I put some interesting contents a found online to achieve developer journey! Main topic ,ruby on rails, git,  back/front end  and another stuff, let me know what you think!
baseurl:     ""
url:         "http://rajohnson-andry.tk"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-139987540-1
google_tag_manager:
# Bing services
bing_verification:

######################################
## Optional features                ##
######################################
animated:             true
show_related_posts:   true
show_post_footers:    True
show_social_icons:    True
ajaxify_contact_form: true
enable_mathjax: true
extended_fonts: true
enable_anchorjs: true

######################################
## Optional site sections           ##
######################################
show_talks_section:     true
show_workshops_section: true

######################################
## Disqus post comments             ##
## (leave blank to disable Disqus)  ##
######################################
disqus_shortname: 'jekyll-blog-2'

##########################################################################
## Facebook Comments plugin                                             ##
## (leave blank to disable Facebook Comments, otherwise set it to true) ##
##########################################################################
facebook_comments: true
facebook_appid: true
facebook_comments_number: 10

###################################
## Social icons                  ##
###################################
github_username: andryjohn
bitbucket_username:
stackoverflow_id:
twitter_username: RajohnsonAndry
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
youtube_channel_id:
bitcoin_url:
paypal_url:
flattr_button:
facebook_username: andry johnson

###################################
## Post sharing icons            ##
###################################
show_sharing_icons: True
# Change to 'true' to enable individual icons
share_facebook: True
share_twitter: True
share_googleplus: True
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: True
share_stumbleupon: false
share_hackernews: True

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'andry1287@gmail.com'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

############################################
## Build settings                         ##
############################################
markdown:     kramdown
mathjax: true
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

#################################################
## Collections (for 'Design' section of site)  ##
#################################################
collections:
  portfolio:
    output: true

plugins:
  - jekyll-seo-tag


plugins: [jekyll-youtube]
 # This will require each of these gems automatically.
